language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- node
- iojs
env:
- TEST=cover
matrix:
  include:
  - node_js: node
    env: TEST=browser-test
sudo: false
before_deploy:
- npm install -g npm
deploy:
  provider: npm
  email: alex@layton.in
  api_key:
    secure: VL8CefQQND6ZP/RRQhdL6w7RJkZ0cH48yzNoDVc47EZn6T5+0n0yKtSvdvE99rEWdIQXiYy5KZ+Fcqi3Mj3VKJAyvMYHhVLuRV7C54wtYAW4zl6Ux027za+emvEbmvt/1NQDP1ziIsBBcI5Q9Rhw6swgVWzlTVkWQRzpfOge//o=
  on:
    node: node
    tags: true
    all_branches: true
    repo: OADA/node-jwks-utils
before_install:
- npm install -g coveralls
script:
- npm run lint
- npm run style
- npm run $TEST
after_success:
- cat ./coverage/lcov.info | coveralls --verbose
